### ISSUE TITLE
Editing or adding changes to GitHub Dark from stylish breaks this GitHub-Selected-Tab-Color

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Selected-Tab-Color#3]
Yep, this is a really odd bug but I confirmed https://github.com/StylishThemes/GitHub-Selected-Tab-Color/issues/1#issuecomment-233531142 just now.

1) Disable Github Dark Script if you have it, and use only stylish,
2) In User Styles (Stylish addon) in Firefox edit GitHub Dark
3) Make some changes and save.
4) Notice  GitHub-Selected-Tab-Color doesnt work anymore.

Workaround is to edit GitHub-Selected-Tab-Color add/remove a space (to trigger save button active) click save and wall GitHub-Selected-Tab-Color works again.

refreshing/ disabling and re-enabling GitHub-Selected-Tab-Color in stylish has no effect here, as far as I can see.

**Comment by Mottie** [comment]
Hey @un1versal!

Actually, that was an issue with [CSS specificity](https://css-tricks.com/specifics-on-css-specificity/) that I encountered yesterday.

What happens is the GitHub Dark style is applied _after_ Stylish adds this style, so the colors are overridden. To overcome this, I added a `body` selector in front of every definition in v1.0.3 (see https://github.com/StylishThemes/GitHub-Selected-Tab-Color/commit/ed8410a01fe1ab252365c30af854f6e0305f1cdb).

Also the selectors in PR #4 were not overriding the GitHub Dark definition because it was using an ID (see CSS specificity for details); but it should now be fixed. Please update to v1.0.5.

**Comment by silverwind** [comment]
Protip: Print out http://www.standardista.com/wp-content/uploads/2012/01/specifishity1.pdf and hang it on your wall!

**Comment by un1versal** [comment]
> Protip: Print out http://www.standardista.com/wp-content/uploads/2012/01/specifishity1.pdf and hang it on your wall!

Unless it has sex appeal, nothing goes on wall :grinning: But mm Ill assign it to a virtual desktop :)
